name: contrib-3d
on:
  schedule:
    - cron: "0 2 * * 1,4"   # twice a week
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: it23372726
          settings: >
            {
              "year": "auto",
              "theme": "night-rainbow"
            }
      - name: Commit files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile-3d-contrib/*
          git commit -m "chore: update 3D contribution graph" || echo "No changes"
          git push

